[package]
name = "dcat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delay-queue = "0.2"
clap = { version = "4.4", features = ["derive"] }

[dev-dependencies]
test_bin = "0.4"
rand = "0.8"
